/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.Consulta;
import Logica.ControladorPacientes;
import Logica.ControladorUsuarios;
import Logica.DtEstudio;
import Logica.IContPaciente;
import Logica.IContUsuario;
import Logica.Medico;
import Logica.NombredeEstudio;
import Logica.Paciente;
import Logica.Prototipo;
import Utils.JFrameConFondo;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ninoh
 */
public class EstudioaPaciente extends JFrameConFondo {

    /**
     * Creates new form EstudioaPaciente
     */
    private final IContPaciente Pct;
    private final IContUsuario Usr;
    List<DtEstudio> Est;
    ArrayList<NombredeEstudio> es;
    ArrayList<Paciente> pa;
    ArrayList<Consulta> co;
    public EstudioaPaciente() {
        initComponents();
        Pct = ControladorPacientes.getInstance();
        Usr = ControladorUsuarios.getInstance();
        Pct.getEstudiosBD();
        Pct.getPacientesdeBD();
        setTitle("Agregar Estudio a Paciente");
        this.setImagen("Fondo.jpg");
        listarEstudios("");
        listarConsultas("");
    }
    
    
        String ConvertirString(String cad) {
        cad = cad.toLowerCase();
        String[] palabras = cad.split("\\s+");
        cad = "";
        for (int i = 0; i < palabras.length; i++) {
            palabras[i].toLowerCase();
            palabras[i] = palabras[i].substring(0, 1).toUpperCase() + palabras[i].substring(1);
            if (i == 0) {
                cad = cad + palabras[i];
            } else {
                cad = cad + " " + palabras[i];
            }
        }
        return cad;
    }
    public void listarEstudios(String nombre) {

        DefaultTableModel modelo = (DefaultTableModel) EstudiosTable.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
        Est = Pct.listarEstudio(nombre);
        for (DtEstudio e : Est) {
            for (Prototipo p : e.getPrototipos()){
                String[] datos = {ConvertirString(String.valueOf(e.getId())),ConvertirString(e.getNombre()),String.valueOf(p.getPrototipo())};
                modelo.addRow(datos);
            }
        }  
    }
    
    /*public void listarConsultas(String ci) {

        DefaultTableModel modelo = (DefaultTableModel) ConsultaTable.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
        co = Pct.listarConsultas();
        for (Consulta dtc : co) {
            String[] datos = {String.valueOf(dtc),ConvertirString(dtc)};
            modelo.addRow(datos);
        }
        
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        EstudiosTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        buscarIngTextField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        ConsultaTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        buscarIngTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        EstudiosTable.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        EstudiosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre de Estudio", "Informe del Protoripo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        EstudiosTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        EstudiosTable.setGridColor(new java.awt.Color(204, 204, 204));
        EstudiosTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EstudiosTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(EstudiosTable);
        if (EstudiosTable.getColumnModel().getColumnCount() > 0) {
            EstudiosTable.getColumnModel().getColumn(1).setPreferredWidth(150);
            EstudiosTable.getColumnModel().getColumn(2).setPreferredWidth(150);
        }

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Buscar Estudio:");

        buscarIngTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarIngTextFieldKeyReleased(evt);
            }
        });

        ConsultaTable.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        ConsultaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha Hora", "Paciente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ConsultaTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        ConsultaTable.setGridColor(new java.awt.Color(204, 204, 204));
        ConsultaTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultaTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(ConsultaTable);
        if (ConsultaTable.getColumnModel().getColumnCount() > 0) {
            ConsultaTable.getColumnModel().getColumn(1).setPreferredWidth(120);
        }

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("Buscar Consulta:");

        buscarIngTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarIngTextField1KeyReleased(evt);
            }
        });

        jButton1.setText("Cancelar");

        jButton2.setText("Agregar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(45, 45, 45)
                                    .addComponent(buscarIngTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(44, 44, 44)
                                    .addComponent(buscarIngTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(buscarIngTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(buscarIngTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EstudiosTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstudiosTableMouseClicked

    }//GEN-LAST:event_EstudiosTableMouseClicked

    private void buscarIngTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarIngTextFieldKeyReleased
        listarEstudios(buscarIngTextField.getText());
    }//GEN-LAST:event_buscarIngTextFieldKeyReleased

    private void ConsultaTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultaTableMouseClicked


    }//GEN-LAST:event_ConsultaTableMouseClicked

    private void buscarIngTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarIngTextField1KeyReleased
        listarConsultas(buscarIngTextField.getText());
    }//GEN-LAST:event_buscarIngTextField1KeyReleased

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        if (EstudiosTable.getRowCount() < 1) {
            JOptionPane.showMessageDialog(this, "No hay ningun Estudio", "Error", JOptionPane.ERROR_MESSAGE);
        }
        if (ConsultaTable.getRowCount() < 1) {
            JOptionPane.showMessageDialog(this, "No hay ningun Paciente", "Error", JOptionPane.ERROR_MESSAGE);
        }
        if (ConsultaTable.getSelectedRow() > -1 && EstudiosTable.getSelectedRow() > -1) {
            List<Paciente> pac;
            boolean b = true, ok=false;
            String ci = (String) ConsultaTable.getValueAt(ConsultaTable.getSelectedRow(), 0);
            String idEst = (String) EstudiosTable.getValueAt(EstudiosTable.getSelectedRow(), 0);
            Medico u = (Medico) Usr.getSesionactiva();
            pac = u.getPacientes();
            if(pac != null){
                for (Paciente p : pac) {
                        if (p.getCi().equals(ci)) {
                            b=false;
                        }
                    }
                    if(b){
                        ok = Pct.AgregarEstudioaPaciente(ci,idEst);
                        if(ok){
                            JOptionPane.showMessageDialog(this, "El estudio ha sido agregado al paciente seleccionado", "Operacion Completada", JOptionPane.ERROR_MESSAGE);
                            this.dispose();
                        }else{
                            JOptionPane.showMessageDialog(this, "No se pudo agregar el estudio al paciente seleccionado", "Error", JOptionPane.ERROR_MESSAGE);
                            this.dispose();
                        }
                    }
                    else{
                        javax.swing.JOptionPane.showMessageDialog(this, "El Paciente no esta asociado a este medico");
                    }
            }
        }
            
        
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstudioaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstudioaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstudioaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstudioaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstudioaPaciente().setVisible(true);
            }
        });
    }
public void centrar(){
        //este metodo devuelve el tamaÃ±o de la pantalla
        int x = (int) (Toolkit.getDefaultToolkit().getScreenSize().getWidth());
        int y = (int) (Toolkit.getDefaultToolkit().getScreenSize().getHeight());
        int h = this.getHeight();
        int z = this.getWidth();
        this.setLocation(x/2-z/2,y/2-h/2);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ConsultaTable;
    private javax.swing.JTable EstudiosTable;
    private javax.swing.JTextField buscarIngTextField;
    private javax.swing.JTextField buscarIngTextField1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
